// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRmn8EDSNogM-RGVxu608FgiGfIGzE7fg',
    appId: '1:512738201389:web:de0124636437ff0fd34da4',
    messagingSenderId: '512738201389',
    projectId: 'inventory-bengkod-flutter',
    authDomain: 'inventory-bengkod-flutter.firebaseapp.com',
    storageBucket: 'inventory-bengkod-flutter.firebasestorage.app',
    measurementId: 'G-Y76B44H49R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUHB0e2kgTOIKeIQrXGrMQe4zSCWDKaC8',
    appId: '1:512738201389:android:e7a07903a7e47359d34da4',
    messagingSenderId: '512738201389',
    projectId: 'inventory-bengkod-flutter',
    storageBucket: 'inventory-bengkod-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACLz19az1xcQNacs7gbH35VaWAO8N5Z4o',
    appId: '1:512738201389:ios:8789a3f15be0cf62d34da4',
    messagingSenderId: '512738201389',
    projectId: 'inventory-bengkod-flutter',
    storageBucket: 'inventory-bengkod-flutter.firebasestorage.app',
    iosBundleId: 'com.example.inventoryManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACLz19az1xcQNacs7gbH35VaWAO8N5Z4o',
    appId: '1:512738201389:ios:8789a3f15be0cf62d34da4',
    messagingSenderId: '512738201389',
    projectId: 'inventory-bengkod-flutter',
    storageBucket: 'inventory-bengkod-flutter.firebasestorage.app',
    iosBundleId: 'com.example.inventoryManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRmn8EDSNogM-RGVxu608FgiGfIGzE7fg',
    appId: '1:512738201389:web:6b888531cb7f0c94d34da4',
    messagingSenderId: '512738201389',
    projectId: 'inventory-bengkod-flutter',
    authDomain: 'inventory-bengkod-flutter.firebaseapp.com',
    storageBucket: 'inventory-bengkod-flutter.firebasestorage.app',
    measurementId: 'G-4JNHJLK2M4',
  );
}
